### ISSUE TITLE
Support ECS Task Execution IAM Role

### ISSUE THREAD

**Issue by justmiles** [justmiles/ecs-cli#1]
Let's consider adding support for invoking the container as a specific [IAM task role](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html). We would assume the IAM role already exists rather than create it on the fly. Whatever is invoking the container would need the `IAM:AssumeRole` permissions for their target role.

```
ecs run --role some-task-role userapp
```

**Comment by zulhfreelancer** [comment]
I'm curious, why you closed this issue? Can we use `--role` flag now?

**Comment by justmiles** [comment]
Yes, there is now a `--role` argument that sets the [task role](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html). This is different from the `--execution-role` [used by AWS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html) to run against Fargate.

**Comment by justmiles** [comment]
I'll update the readme with the updated flag.
