### ISSUE TITLE
How to use custom AWS profile?

### ISSUE THREAD

**Issue by zulhfreelancer** [justmiles/ecs-cli#3]
Does it possible to use `--profile` flag when running this tool? Something like [this](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html#using-profiles).

**Comment by justmiles** [comment]
Right now it only supports exporting AWS_PROFILE or setting it as the default in your AWS config file. This solves for most use cases but PRs are always welcome.
