### ISSUE TITLE
How to make this interactive like SSH session?

### ISSUE THREAD

**Issue by zulhfreelancer** [justmiles/ecs-cli#5]
After giving this a try, I think this tool is good to run one-off task i.e. DB migration script. I wonder if I can turn this into something interactive like SSH window where I can run any command in the shell running in the task's container.

How to achieve that point from the current point? Any tips to share? Ideally, I want to do this on Fargate. I don't mind submitting a PR for that if it's not complex to implement.

From my latest tests, I try to run a Docker container with SSH daemon running inside. But it's not working. I mean, it's not interactive.

Appreciate your inputs here, @justmiles.

**Comment by justmiles** [comment]
Hi - AWS [recently released Amazon ECS Exec](https://aws.amazon.com/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/). We can use this to open a session inside containers.
